// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnvQz0lveGnbsSoJkMg9X0JtM9OktYAko',
    appId: '1:724904855807:web:86d3bec461ece6c73364ca',
    messagingSenderId: '724904855807',
    projectId: 'fitness-nakul',
    authDomain: 'fitness-nakul.firebaseapp.com',
    storageBucket: 'fitness-nakul.appspot.com',
    measurementId: 'G-Q3VBK4CHH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkFwc4a9qU2bFelwYyi72eBzzc_PpVnk',
    appId: '1:724904855807:android:1cfb7ca818413a9a3364ca',
    messagingSenderId: '724904855807',
    projectId: 'fitness-nakul',
    storageBucket: 'fitness-nakul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXikvMl1qXcW74yIqoYlTuktiW7KUj3hY',
    appId: '1:724904855807:ios:6b2631e56975c0453364ca',
    messagingSenderId: '724904855807',
    projectId: 'fitness-nakul',
    storageBucket: 'fitness-nakul.appspot.com',
    iosBundleId: 'com.example.androidproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXikvMl1qXcW74yIqoYlTuktiW7KUj3hY',
    appId: '1:724904855807:ios:13165c8e27efdc703364ca',
    messagingSenderId: '724904855807',
    projectId: 'fitness-nakul',
    storageBucket: 'fitness-nakul.appspot.com',
    iosBundleId: 'com.example.androidproj.RunnerTests',
  );
}
